stages:
  - deploy
  - notification

cache:
  paths:
    - backend/node_modules/

deploy:
  stage: deploy
  only:
    - production # только для этой ветки
  script:
    - sh deploy/.ci-notify.sh "Собираю проект парсер ☺️" $TELEGRAM_BOT_TOKEN $TELEGRAM_CHAT_ID || true
    - docker-compose stop rate
    - docker-compose build --pull
    - sh deploy/.ci-notify.sh "Перезапускаю контейнеры 🥳" $TELEGRAM_BOT_TOKEN $TELEGRAM_CHAT_ID || true
    - docker-compose down --remove-orphans
    - docker-compose up -d --no-build
    - sh deploy/.ci-notify.sh "Контейнеры успешно запущены! 🥰" $TELEGRAM_BOT_TOKEN $TELEGRAM_CHAT_ID || true
    - docker image prune -f
  when: always
  except:
    - master # исключить ветки
  tags:
    - docker

notify_error:
  stage: notification
  only:
    - production
  tags:
    - docker
  script:
    - sh deploy/.ci-notify.sh "Упс, что-то пошло не так... 😔"
    - docker-compose start rate
  when: on_failure