stages:
  - deploy
  - notification

cache:
  paths:
    - backend/node_modules/

deploy:
  stage: deploy
  only:
    - production # только для этой ветки
  script:
    - sudo sh deploy/.ci-notify.sh "Собираю проект ☺️" || true
    - docker-compose build --pull
    - sudo sh deploy/.ci-notify.sh "Перезапускаю контейнеры 🥳" || true
    - docker-compose down --remove-orphans
    - docker-compose up -d --build
    - sudo sh deploy/.ci-notify.sh "Контейнеры успешно запущены! 🥰" || true
  when: always
  except:
    - master # исключить ветки
  tags:
    - docker

notify_error:
  stage: notification
  only:
    - production
  tags:
    - notification
  script:
    - sh deploy/.ci-notify.sh "Упс, что-то пошло не так... 😔"
  when: on_failure