version: "2"
services:
  rate:
    container_name: rate
    restart: always
    depends_on:
      - mongo-rate
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    links:
      - mongo-rate

  mongo-rate:
    container_name: mongo-rate
    restart: always
    image: mongo
    volumes:
      - ./docker/mongo-seed/db:/data/db
    ports:
      - "27017:27017"

#  mongo-rate-seed:
#    container_name: mongo-rate-seed
#    depends_on:
#      - mongo-rate
#    build:
#      context: .
#      dockerfile: docker/mongo-seed/Dockerfile
#    links:
#      - mongo-rate