version: "3"

services:
  admin-service:
    build: ../isvn-admin-service
    container_name: isvn-admin-service
    command: java -jar -Xms256M -Xmx1g
      -Dfile.encoding=UTF-8 -Dspring.profiles.active=prod
      -Dsecurity.oauth2.resource.userInfoUri=http://10.8.0.206:8080/auth/realms/isvn/protocol/openid-connect/userinfo
      -Disvn.filenet-service.base-url=http://filenet-service:8081
      -Disvn.menu-service.base-url=http://menu-service:8085
      -Disvn.task-service.base-url=http://task-service:8084
      -Disvn.ui-service.base-url=http://ui-service:8082
      -Disvn.reports-service.base-url=http://reports-service:8087
      -Disvn.integration-service.base-url=http://integration-service:8088
      -Disvn.admin-service.base-url=http://admin-service:8089
      -Disvn.notification-service.base-url=http://notification-service:8092
      isvn-admin-service.jar
    restart: always
    ports:
      - 8089:8089
    volumes:
      - /opt:/opt
    env_file:
      - local.env
    environment:
      - SERVER_PORT=8089

  filenet-service:
    build: ../isvn-filenet-service
    container_name: isvn-filenet-service
    command: java -jar -Xms256M -Xmx1g
      -Dfile.encoding=UTF-8
      -Dspring.profiles.active=prod
      -Dsecurity.oauth2.resource.userInfoUri=http://10.8.0.206:8080/auth/realms/isvn/protocol/openid-connect/userinfo
      -Disvn.filenet-service.base-url=http://filenet-service:8081
      -Disvn.menu-service.base-url=http://menu-service:8085
      -Disvn.task-service.base-url=http://task-service:8084
      -Disvn.ui-service.base-url=http://ui-service:8082
      -Disvn.reports-service.base-url=http://reports-service:8087
      -Disvn.integration-service.base-url=http://integration-service:8088
      -Disvn.admin-service.base-url=http://admin-service:8089
      -Disvn.notification-service.base-url=http://notification-service:8092
      isvn-filenet-service.jar
    restart: always
    ports:
      - 8081:8081
    volumes:
      - /opt:/opt
    env_file:
      - local.env
    environment:
      - SERVER_PORT=8081

  gateway-service:
    build: ../isvn-gateway-service
    container_name: isvn-gateway-service
    command: java -jar -Xms256M -Xmx1g
      -Dfile.encoding=UTF-8
      -Dspring.profiles.active=prod
      -Dsecurity.oauth2.resource.userInfoUri=http://10.8.0.206:8080/auth/realms/isvn/protocol/openid-connect/userinfo
      -Dsecurity.oauth2.client.accessTokenUri=http://10.8.0.206:8080/auth/realms/isvn/protocol/openid-connect/token
      -Dsecurity.oauth2.client.userAuthorizationUri=http://10.8.0.206:8080/auth/realms/isvn/protocol/openid-connect/auth
      -Dsecurity.oauth2.client.userLogoutUri="https://blitz/login/logout?redirect="
      -Dzuul.routes.filenet.url=http://filenet-service:8081
      -Dzuul.routes.menu.url=http://menu-service:8085
      -Dzuul.routes.task.url=http://task-service:8084
      -Dzuul.routes.ui.url=http://ui-service:8082
      -Dzuul.routes.report.url=http://reports-service:8087
      -Dzuul.routes.integration.url=http://integration-service:8088
      -Dzuul.routes.admin.url=http://admin-service:8089
      -Dzuul.routes.notification.url=http://notification-service:8092
      isvn-gateway-service.jar
    restart: always
    ports:
      - 8086:8086
    volumes:
      - /opt:/opt
    env_file:
      - local.env
    environment:
      - SERVER_PORT=8086

  integration-service:
    build: ../isvn-integration-service
    container_name: isvn-integration-service
    command: java -jar -Xms256M -Xmx1g
      -Dfile.encoding=UTF-8
      -Dspring.profiles.active=prod
      -Dsecurity.oauth2.resource.userInfoUri=http://10.8.0.206:8080/auth/realms/isvn/protocol/openid-connect/userinfo
      -Disvn.internalUser.accessTokenUri=http://10.8.0.206:8080/auth/realms/isvn/protocol/openid-connect/token
      -Disvn.filenet-service.base-url=http://filenet-service:8081
      -Disvn.menu-service.base-url=http://menu-service:8085
      -Disvn.task-service.base-url=http://task-service:8084
      -Disvn.ui-service.base-url=http://ui-service:8082
      -Disvn.reports-service.base-url=http://reports-service:8087
      -Disvn.integration-service.base-url=http://integration-service:8088
      -Disvn.admin-service.base-url=http://admin-service:8089
      -Disvn.notification-service.base-url=http://notification-service:8092
      isvn-integration-service.jar
    restart: always
    ports:
      - 8088:8088
    volumes:
      - /opt:/opt
    env_file:
      - local.env
    environment:
      - SERVER_PORT=8088

  menu-service:
    build: ../isvn-menu-service
    container_name: isvn-menu-service
    command: java -jar -Xms256M -Xmx1g
      -Dfile.encoding=UTF-8
      -Dspring.profiles.active=prod
      -Dsecurity.oauth2.resource.userInfoUri=http://10.8.0.206:8080/auth/realms/isvn/protocol/openid-connect/userinfo
      -Disvn.filenet-service.base-url=http://filenet-service:8081
      -Disvn.menu-service.base-url=http://menu-service:8085
      -Disvn.task-service.base-url=http://task-service:8084
      -Disvn.ui-service.base-url=http://ui-service:8082
      -Disvn.reports-service.base-url=http://reports-service:8087
      -Disvn.integration-service.base-url=http://integration-service:8088
      -Disvn.admin-service.base-url=http://admin-service:8089
      -Disvn.notification-service.base-url=http://notification-service:8092
      isvn-menu-service.jar
    restart: always
    ports:
      - 8085:8085
    volumes:
      - /opt:/opt
    env_file:
      - local.env
    environment:
      - SERVER_PORT=8085

  notification-service:
    build: ../isvn-notification-service
    container_name: isvn-notification-service
    command: java -jar -Xms256M -Xmx1g
      -Dfile.encoding=UTF-8
      -Dspring.profiles.active=prod
      -Dsecurity.oauth2.resource.userInfoUri=http://10.8.0.206:8080/auth/realms/isvn/protocol/openid-connect/userinfo
      -Disvn.internalUser.accessTokenUri=http://10.8.0.206:8080/auth/realms/isvn/protocol/openid-connect/token
      -Disvn.filenet-service.base-url=http://filenet-service:8081
      -Disvn.menu-service.base-url=http://menu-service:8085
      -Disvn.task-service.base-url=http://task-service:8084
      -Disvn.ui-service.base-url=http://ui-service:8082
      -Disvn.reports-service.base-url=http://reports-service:8087
      -Disvn.integration-service.base-url=http://integration-service:8088
      -Disvn.admin-service.base-url=http://admin-service:8089
      -Disvn.notification-service.base-url=http://notification-service:8092
      isvn-notification-service.jar
    restart: always
    ports:
      - 8092:8092
    volumes:
      - /opt:/opt
    env_file:
      - local.env
    environment:
      - SERVER_PORT=8092

  reports-service:
    build: ../isvn-reports-service
    container_name: isvn-reports-service
    command: java -jar -Xms256M -Xmx1g
      -Dfile.encoding=UTF-8
      -Dspring.profiles.active=prod
      -Dsecurity.oauth2.resource.userInfoUri=http://10.8.0.206:8080/auth/realms/isvn/protocol/openid-connect/userinfo
      -Disvn.filenet-service.base-url=http://filenet-service:8081
      -Disvn.menu-service.base-url=http://menu-service:8085
      -Disvn.task-service.base-url=http://task-service:8084
      -Disvn.ui-service.base-url=http://ui-service:8082
      -Disvn.reports-service.base-url=http://reports-service:8087
      -Disvn.integration-service.base-url=http://integration-service:8088
      -Disvn.admin-service.base-url=http://admin-service:8089
      -Disvn.notification-service.base-url=http://notification-service:8092
      isvn-reports-service.jar
    restart: always
    ports:
      - 8087:8087
    volumes:
      - /opt:/opt
    env_file:
      - local.env
    environment:
      - SERVER_PORT=8087

  task-service:
    build: ../isvn-task-tracker-service
    container_name: isvn-task-tracker-service
    command: java -jar -Xms256M -Xmx2g -Dfile.encoding=UTF-8
      -Dspring.profiles.active=prod
      -Dsecurity.oauth2.resource.userInfoUri=http://10.8.0.206:8080/auth/realms/isvn/protocol/openid-connect/userinfo
      -Dsearch.enabled=true
      -Disvn.filenet-service.base-url=http://filenet-service:8081
      -Disvn.menu-service.base-url=http://menu-service:8085
      -Disvn.task-service.base-url=http://task-service:8084
      -Disvn.ui-service.base-url=http://ui-service:8082
      -Disvn.reports-service.base-url=http://reports-service:8087
      -Disvn.integration-service.base-url=http://integration-service:8088
      -Disvn.admin-service.base-url=http://admin-service:8089
      -Disvn.notification-service.base-url=http://notification-service:8092
      isvn-task-tracker-service.jar
    restart: always
    ports:
      - 8084:8084
    volumes:
      - /opt:/opt
    env_file:
      - local.env
    environment:
      - SERVER_PORT=8084

  ui-service:
    build: ../isvn-ui-service
    container_name: isvn-ui-service
    command: java -jar -Xms256M -Xmx1g
      -Dfile.encoding=UTF-8
      -Dspring.profiles.active=prod
      -Dsecurity.oauth2.resource.userInfoUri=http://10.8.0.206:8080/auth/realms/isvn/protocol/openid-connect/userinfo
      -Dsearch.enabled=true
      -Disvn.filenet-service.base-url=http://filenet-service:8081
      -Disvn.menu-service.base-url=http://menu-service:8085
      -Disvn.task-service.base-url=http://task-service:8084
      -Disvn.ui-service.base-url=http://ui-service:8082
      -Disvn.reports-service.base-url=http://reports-service:8087
      -Disvn.integration-service.base-url=http://integration-service:8088
      -Disvn.admin-service.base-url=http://admin-service:8089
      -Disvn.notification-service.base-url=http://notification-service:8092
      isvn-ui-service.jar
    restart: always
    ports:
      - 8082:8082
    volumes:
      - /opt:/opt
    env_file:
      - local.env
    environment:
      - SERVER_PORT=8082

  abac-service:
    build: /home/user/
    container_name: isvn-abac-service
    restart: always
    ports:
      - 9090:9090
