#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged
## Prettify all selected files
#echo "$FILES" | xargs ./node_modules/.bin/prettier --write --config ../backend/.prettierrc --check "src/**/**/*.ts"
#
## Add back the modified/prettified files to staging
#echo "$FILES" | xargs git add

exit 0